(cl:defpackage pavlov_mini_msgs-srv
  (:use )
  (:export
   "CONNECT_SERVOS"
   "<CONNECT_SERVOS-REQUEST>"
   "CONNECT_SERVOS-REQUEST"
   "<CONNECT_SERVOS-RESPONSE>"
   "CONNECT_SERVOS-RESPONSE"
   "SET_FACE"
   "<SET_FACE-REQUEST>"
   "SET_FACE-REQUEST"
   "<SET_FACE-RESPONSE>"
   "SET_FACE-RESPONSE"
   "SET_GAIT"
   "<SET_GAIT-REQUEST>"
   "SET_GAIT-REQUEST"
   "<SET_GAIT-RESPONSE>"
   "SET_GAIT-RESPONSE"
   "SET_MOTOR_CALIBRATION"
   "<SET_MOTOR_CALIBRATION-REQUEST>"
   "SET_MOTOR_CALIBRATION-REQUEST"
   "<SET_MOTOR_CALIBRATION-RESPONSE>"
   "SET_MOTOR_CALIBRATION-RESPONSE"
  ))

