controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - waist_joint
      - shoulder_joint
      - elbow_joint
      - wrist_joint
      - wrist_pitch_joint
  - name: fake_leg1_group_controller
    type: $(arg fake_execution_type)
    joints:
      - leg_1_1_joint
      - leg_1_2_joint
      - leg_1_3_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_joint
  - name: fake_leg2_group_controller
    type: $(arg fake_execution_type)
    joints:
      - leg_2_1_joint
      - leg_2_2_joint
      - leg_2_3_joint
  - name: fake_leg3_group_controller
    type: $(arg fake_execution_type)
    joints:
      - leg_3_1_joint
      - leg_3_2_joint
      - leg_3_3_joint
  - name: fake_leg4_group_controller
    type: $(arg fake_execution_type)
    joints:
      - leg_4_1_joint
      - leg_4_2_joint
      - leg_4_3_joint
  - name: fake_legs13_group_controller
    type: $(arg fake_execution_type)
    joints:
      - leg_1_1_joint
      - leg_1_2_joint
      - leg_1_3_joint
      - leg_3_1_joint
      - leg_3_2_joint
      - leg_3_3_joint
  - name: fake_legs24_group_controller
    type: $(arg fake_execution_type)
    joints:
      - leg_2_1_joint
      - leg_2_2_joint
      - leg_2_3_joint
      - leg_4_1_joint
      - leg_4_2_joint
      - leg_4_3_joint
  - name: fake_leg_2_3_4_group_controller
    type: $(arg fake_execution_type)
    joints:
      - leg_2_1_joint
      - leg_2_2_joint
      - leg_2_3_joint
      - leg_3_1_joint
      - leg_3_2_joint
      - leg_3_3_joint
      - leg_4_1_joint
      - leg_4_2_joint
      - leg_4_3_joint
  - name: fake_leg_1_3_4_group_controller
    type: $(arg fake_execution_type)
    joints:
      - leg_1_1_joint
      - leg_1_2_joint
      - leg_1_3_joint
      - leg_3_1_joint
      - leg_3_2_joint
      - leg_3_3_joint
      - leg_4_1_joint
      - leg_4_2_joint
      - leg_4_3_joint
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: grab_object
  - group: leg1_group
    pose: sit_pose_1
  - group: gripper
    pose: grip_closed
  - group: leg2_group
    pose: sit_pose_2
  - group: leg3_group
    pose: sit_pose_3
  - group: leg4_group
    pose: sit_pose_4
  - group: legs13_group
    pose: zero_position_s1
  - group: legs24_group
    pose: zero_position_s2
  - group: leg_2_3_4_group
    pose: walking_leg_1_s2
  - group: leg_1_3_4_group
    pose: walking_leg_2_s2