# obstacle_range: 10
# raytrace_range: 10
# max_obstacle_height: 2.0
# inf_is_valid: true
# footprint: [[0.01, 0.01], [-0.01, 0.01], [-0.01, -0.01], [0.01, -0.01]]

# inflation_radius: 0.0
# costscalingfactor: 1.3

# map_topic: /map
# subscribe_to_updates: true
# observation_sources: laser_scan_sensor
# laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
# global_frame: map
# robot_base_frame: base_link
# always_send_full_costmap: true

#---standard pioneer footprint---
#---(in meters)---
robot_radius: 0.17


transform_tolerance: 0.2
map_type: costmap

obstacle_layer:
 enabled: true
 obstacle_range: 3.0
 raytrace_range: 4.0
 inflation_radius: 0.1
 track_unknown_space: true
 combination_method: 1

 observation_sources: laser_scan_sensor
 laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}


inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.1  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "/rtabmap/grid_map"